### ISSUE TITLE
Tasks in the gulpfile with gulp-hub call never run

### ISSUE THREAD

**Issue by robatron** [frankwallis/gulp-hub#13]
We discovered that if one has tasks in a gulpfile alongside a gulp-hub call, those tasks are never run. I'm assuming b/c gulp-hub overwrites tasks with a collection of tasks of the same name in gulpfiles matched by gulp-hub.

Not super pressing as the workaround is to simply not include tasks in a gulpfile that calls gulp-hub; just wanted to record the issue.

**Comment by frankwallis** [comment]
I hope this is also addressed by my latest changes, thanks.

**Comment by frankwallis** [comment]
closing
