### ISSUE TITLE
gulp 4.0 custom registry updates

### ISSUE THREAD

**Issue by phated** [frankwallis/gulp-hub#24]
We've been working on custom registries and have changed the way they are defined.  Please see https://github.com/phated/undertaker/issues/25 and https://github.com/phated/undertaker/commit/21cafaa7981b1fc21d8a42debf10cf18e4308a6b for the new implementation/spec.

Also, some people are looking to use gulp-hub to load a bunch of tasks, but they are running into "forward referencing" problems.  I made a custom registry at https://github.com/undertakerjs/undertaker-forward-reference to allow forward referencing tasks.  I think you should inherit from that or implement similar functionality,

**Comment by phated** [comment]
@frankwallis pinging

**Comment by frankwallis** [comment]
I've created a 'registry-init' branch with minimal updates to support the new registry api. 

I also had a look at the forward reference stuff, but got a bit stuck. I'm not sure I can use the forward-reference package because it conflicts with the hub registry, but I should be able to implement the same functionality in the hub. If someone could provide an example of what they are trying to do then that would make my life a lot easier.

**Comment by bradcerasani** [comment]
Splitting gulp tasks between multiple files is a very common use case IMO.

More colour here:
https://github.com/gulpjs/gulp/issues/972
https://github.com/gulpjs/gulp/issues/1028
https://github.com/gulpjs/gulp/issues/1038

**Comment by phated** [comment]
@bradcerasani it is not the recommended pattern to load multiple sub-gulpfiles or files that call gulp.task, but instead to export functions and combine everything using gulp.task in your main gulpfile.  Even so, in gulp 4.0, gulp-hub is the recommended community module for this pattern if you can't or won't use the recommended pattern.  However, I don't understand what your comment is adding to this thread.

**Comment by mryellow** [comment]
> it is not the recommended pattern to load multiple sub-gulpfiles or files that call gulp.task

That's entirely one of the most beneficial features of the entire Gulp ecosystem when it comes to task organisation.
