### ISSUE TITLE
I upgraded from Node 4 to Node 6 and this module stopped working

### ISSUE THREAD

**Issue by BorisKozo** [frankwallis/gulp-hub#31]
The issue is probably with how NPM 3 re-arranges the node_modules.

I tried debugging the code but didn't figure it out.

I have the most simple case:

````
Project A
   |
   |- gulpfile.js
   |- Project B
           |
           |- gulpfile.js
````

I am loading the gulpfile in Project B from the gulpfile in project A via
hub('./ProjectB/gulpfile.js');

It says ````Loaded ProjectB/gulpfile.js````

But then cannot find the task which is within that inner gulpfile.

Edit: I am on Windows

**Comment by BorisKozo** [comment]
I think I found the issue.
Are you still maintaining this module?
Would you accept a PR with the fix?

**Comment by BorisKozo** [comment]
:(

**Comment by robatron** [comment]
Thanks for your patience; I've been busy. Yes, I would love to see your PR!
