### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by mohitt** [frankwallis/gulp-hub#35]
Can someone please look into this. 

https://github.com/FountainJS/generator-fountain-angular1/issues/63

gulp.registry is not a function

**Comment by baywet** [comment]
Solved it add this to both dev deps and deps, I guess the fix is to come in the next version.
"gulp": "github:gulpjs/gulp#4.0",
"gulp-hub": "github:frankwallis/gulp-hub#4.0",
