### ISSUE TITLE
Publish 4.1.0 to NPM

### ISSUE THREAD

**Issue by MatissJanis** [frankwallis/gulp-hub#37]
NPM currently has the last version as 0.8.0

https://www.npmjs.com/package/gulp-hub

**Comment by frankwallis** [comment]
I have published 4.1.1 to npm now, thanks

**Comment by MatissJanis** [comment]
Awesome!

**Comment by svenvandescheur** [comment]
Npm now shows 0.8.0, is something wrong?

**Comment by frankwallis** [comment]
gulp-hub for gulp4 was previously only published as `gulp-hub@next` so I suspect you were seeing the version for gulp3. I have now published the gulp4 version as `@latest` so that is what you should now get if you run `npm install gulp-hub`
