### ISSUE TITLE
Latest version of gulp-hub at NPM is 4.1.0, and it's broken

### ISSUE THREAD

**Issue by sadasant** [frankwallis/gulp-hub#39]
Hi peeps!

The lovely greenkeeper bot updated our projects to gulp-hub 4.1.0 and now they are all broken 😅 please unpublish it while it's under development ❤️

See: https://www.npmjs.com/package/gulp-hub

**Comment by Tickthokk** [comment]
I might be experiencing something similar.  I'm using the example at the above link verbatim.

```
$ node -v; npm -v
v7.8.0
4.2.0
```

> `TypeError: gulp.registry is not a function`

```
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-hub": "^4.1.0"
  },
```

**Comment by frankwallis** [comment]
gulp-hub@4.1.0 is for use with gulp4, for gulp3 use gulp-hub@0.8.0
```
npm install gulp-hub@0.8.0 --save-dev
```

**Comment by frankwallis** [comment]
I have updated the tags in npm so that gulp-hub@0.8.0 is now tagged as latest and installed by default. To install gulp-hub4 use ```npm install gulp-hub@next```.
