### ISSUE TITLE
Replace deprecated gulp-util package by fancy-log package

### ISSUE THREAD

**Issue by faelplg** [frankwallis/gulp-hub#41]
Hello, thanks for this nice package. This a simple issue.

You are using `gulp-util` package for console logging and it is deprecated.

Consider replacing this package by [fancy-log](https://www.npmjs.com/package/fancy-log) as described in [gulp-util page](https://github.com/gulpjs/gulp-util).

**Comment by frankwallis** [comment]
Thanks for the heads up, this is resolved in 4.2.0
