### ISSUE TITLE
gulpfile.js with non-identical tasks

### ISSUE THREAD

**Issue by xtianares** [frankwallis/gulp-hub#46]
I have project with multiple sub-projects with this folder structure:

.\gulpfile.js
.\subProjectA\gulpfile.js
.\subProjectB\gulpfile.js

The gulpfiles.js of subProjectA and subProjectB are not identical as far as the tasks and it seems that gulp-hub only works with gulpfiles with completely identical tasks. I was under the impression that it should still work with my setup, right?

While running a default task, the default task of subProjectA\gulpfile.js is now also dependent on the default task's dependency of subProjectB\gulpfile.js

**Comment by frankwallis** [comment]
This does not sound right, can you paste the output of 'gulp --tasks' please?

**Comment by xtianares** [comment]
sorry, I decided to go with a different route to get a setup like this to work.
