### ISSUE TITLE
Is there an issue with the plugin when downloading from Docker/Kubernetes container

### ISSUE THREAD

**Issue by vrajannagari** [frankwallis/gulp-hub#47]
Hello,
I am trying to do the npm install with loglevel silly and save-dev, save-exact and keep running into issue everytime when it is trying to fetch/extract the frankwallis/gulp-hub. Is there a know issue ? Please advise

Here is the exact command i used for this : **time npm install --no-spin -D -E -ddd**

xyz:xyz vrajannagari$ **npm -v && node -v
6.11.3
v10.17.0**
**Docker image** : node:jessie-dubnium

**Docker container on Macbook**:
npm sill pacote git manifest for gulp-hub@github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4 fetched in **1108ms**

**Container on Kubernetes**: 
Here is what I see in the log for frankwallis/gulp-hub and it is taking a few attempts to work and taking very long.
npm sill resolveWithNewModule webpack-split-by-path@0.0.10 checking installable status
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/frankwallis/gulp-hub.git attempt # 2
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/frankwallis/gulp-hub.git attempt # 3
npm **info lifecycle** gulp-hub@4.1.0~prepack: gulp-hub@4.1.0
npm info lifecycle gulp-hub@4.1.0~postpack: gulp-hub@4.1.0
npm **sill pacote git manifest** for gulp-hub@github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4 fetched in **386875ms(6.45 minutes)**
npm sill resolveWithNewModule gulp-hub@4.1.0 checking installable status

npm sill **extract** rxjs@^5.5.6 extracted to /greenstack-portal/node_modules/.staging/rxjs-3c55f083 (10823ms)
**npm sill pacote Retrying git command: ls-remote -h -t git://github.com/frankwallis/gulp-hub.git attempt # 2
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/frankwallis/gulp-hub.git attempt # 3**
npm sill extract gulp-hub@github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4 extracted to /greenstack-portal/node_modules/.staging/gulp-hub-cf71f72a (386084ms)
npm timing action:extract Completed in **386648ms**

**Comment by frankwallis** [comment]
I'm not aware of any issues. Why are you installing from the git repository instead of the published npm package?

**Comment by vrajannagari** [comment]
Thanks @frankwallis  I do not know if there was a reason for not using npm package by the team and instead using github .However FYI when I updated the package.json for the gulp-hub package version it worked fast.

**Comment by frankwallis** [comment]
Probably just a hangover when moving from gulp3 -> gulp4. I am glad it is working for you now.
